export const menuSections = [
  {
    id: "entrees",
    title: { fr: "Entrées", en: "Starters", es: "Entrantes" },
    items: [
      { name: { fr: "Chèvre chaud", en: "Warm goat cheese", es: "Queso de cabra caliente" }, price: "7,50 €" },
      { name: { fr: "Burrata", en: "Burrata", es: "Burrata" }, price: "8,00 €" },
      { name: { fr: "Carpaccio de saumon", en: "Salmon carpaccio", es: "Carpaccio de salmón" }, price: "9,00 €" },
      { name: { fr: "Escargots beurrés à l'ail × 6", en: "Garlic butter snails × 6", es: "Caracoles con mantequilla de ajo × 6" }, price: "8,50 €" },
      { name: { fr: "Escargots beurrés à l'ail × 12", en: "Garlic butter snails × 12", es: "Caracoles con mantequilla de ajo × 12" }, price: "14,50 €" },
      { name: { fr: "Tomate Mozzarella", en: "Tomato Mozzarella", es: "Tomate Mozzarella" }, price: "7,50 €" },
    ],
  },
  {
    id: "salades",
    title: { fr: "Salades", en: "Salads", es: "Ensaladas" },
    items: [
      {
        name: { fr: "Salade B-H-V", en: "B-H-V Salad", es: "Ensalada B-H-V" },
        desc: { fr: "Salade · tomate · avocat · crevette · saumon · maïs · orange · pomme · mozzarella · citron", en: "Lettuce · tomato · avocado · shrimp · salmon · corn · orange · apple · mozzarella · lemon", es: "Lechuga · tomate · aguacate · gambas · salmón · maíz · naranja · manzana · mozzarella · limón" },
        price: "19,50 €",
      },
      {
        name: { fr: "Salade Composée", en: "Mixed Salad", es: "Ensalada Mixta" },
        desc: { fr: "Salade · maïs · tomate · œuf dur · avocat", en: "Lettuce · corn · tomato · hard-boiled egg · avocado", es: "Lechuga · maíz · tomate · huevo duro · aguacate" },
        price: "10,50 €",
      },
      {
        name: { fr: "Salade César", en: "Caesar Salad", es: "Ensalada César" },
        desc: { fr: "Salade · maïs · tomate · croûtons · filet de poulet", en: "Lettuce · corn · tomato · croutons · chicken fillet", es: "Lechuga · maíz · tomate · picatostes · filete de pollo" },
        price: "14,50 €",
      },
      {
        name: { fr: "Salade de Chèvre Chaud", en: "Warm Goat Cheese Salad", es: "Ensalada de Queso de Cabra" },
        desc: { fr: "Salade · maïs · tomate · mimolette · pesto · pain toasté · chèvre · miel", en: "Lettuce · corn · tomato · mimolette · pesto · toast · goat cheese · honey", es: "Lechuga · maíz · tomate · mimolette · pesto · pan tostado · queso de cabra · miel" },
        price: "14,50 €",
      },
      {
        name: { fr: "Salade Italienne", en: "Italian Salad", es: "Ensalada Italiana" },
        desc: { fr: "Salade · tomate · mozzarella · jambon de Parme · olives · parmesan · roquette · basilic", en: "Lettuce · tomato · mozzarella · Parma ham · olives · parmesan · rocket · basil", es: "Lechuga · tomate · mozzarella · jamón de Parma · aceitunas · parmesano · rúcula · albahaca" },
        price: "15,00 €",
      },
    ],
  },
  {
    id: "grillades",
    title: { fr: "Grillades", en: "Grills", es: "Parrilla" },
    note: {
      fr: "Garnitures au choix : riz · purée · haricot vert · salade · frites — Garniture supplémentaire : 3,50 €",
      en: "Choice of side: rice · mash · green beans · salad · fries — Extra side: €3.50",
      es: "Guarnición a elegir: arroz · puré · judías verdes · ensalada · patatas — Guarnición extra: 3,50 €",
    },
    items: [
      { name: { fr: "Entrecôte", en: "Ribeye Steak", es: "Entrecot" }, desc: { fr: "250 g — frites et salade", en: "250g — fries and salad", es: "250g — patatas fritas y ensalada" }, price: "22,00 €" },
      { name: { fr: "Faux-filet", en: "Sirloin Steak", es: "Solomillo" }, desc: { fr: "220 g — frites et salade", en: "220g — fries and salad", es: "220g — patatas fritas y ensalada" }, price: "21,00 €" },
      { name: { fr: "Filet de bœuf", en: "Beef Tenderloin", es: "Filete de ternera" }, desc: { fr: "220 g — pomme sautée · haricot vert · sauce graisse de canard", en: "220g — sautéed potatoes · green beans · duck fat sauce", es: "220g — patatas salteadas · judías verdes · salsa de grasa de pato" }, price: "26,00 €" },
      { name: { fr: "Côte de bœuf", en: "Beef Rib", es: "Chuletón" }, desc: { fr: "Garniture au choix", en: "Choice of side", es: "Guarnición a elegir" }, price: "38,00 €" },
      { name: { fr: "Confit de canard", en: "Duck Confit", es: "Confit de pato" }, desc: { fr: "Pomme sautée à l'ail", en: "Garlic sautéed potatoes", es: "Patatas salteadas con ajo" }, price: "17,50 €" },
      { name: { fr: "Magret de canard", en: "Duck Breast", es: "Magret de pato" }, desc: { fr: "Purée de légumes", en: "Vegetable mash", es: "Puré de verduras" }, price: "19,50 €" },
    ],
  },
  {
    id: "pates",
    title: { fr: "Pâtes", en: "Pasta", es: "Pastas" },
    items: [
      { name: { fr: "Escalope Normande", en: "Normandy Escalope", es: "Escalopa Normanda" }, desc: { fr: "Escalope de veau · crème fraîche · champignons · sauce Normande", en: "Veal escalope · crème fraîche · mushrooms · Normandy sauce", es: "Escalopa de ternera · crème fraîche · champiñones · salsa normanda" }, price: "14,50 €" },
      { name: { fr: "Tagliatelles filet de poulet", en: "Chicken Tagliatelle", es: "Tagliatelle de pollo" }, desc: { fr: "Sauce Normande aux champignons", en: "Normandy mushroom sauce", es: "Salsa normanda con champiñones" }, price: "14,50 €" },
      { name: { fr: "Tagliatelles au saumon", en: "Salmon Tagliatelle", es: "Tagliatelle de salmón" }, desc: { fr: "Pâtes tagliatelles et saumon", en: "Tagliatelle pasta and salmon", es: "Pasta tagliatelle y salmón" }, price: "14,50 €" },
      { name: { fr: "Tagliatelles Carbonara", en: "Carbonara Tagliatelle", es: "Tagliatelle Carbonara" }, desc: { fr: "Lardons · jaune d'œuf · parmesan", en: "Bacon bits · egg yolk · parmesan", es: "Bacon · yema de huevo · parmesano" }, price: "15,50 €" },
    ],
  },
  {
    id: "poissons",
    title: { fr: "Poissons", en: "Fish", es: "Pescados" },
    items: [
      { name: { fr: "Pavé de saumon", en: "Salmon Fillet", es: "Filete de salmón" }, desc: { fr: "Purée · légumes · sauce beurre à l'ail et persil", en: "Mash · vegetables · garlic parsley butter sauce", es: "Puré · verduras · salsa de mantequilla al ajo y perejil" }, price: "16,50 €" },
      { name: { fr: "Daurade Royale", en: "Sea Bream", es: "Dorada Real" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "24,00 €" },
    ],
  },
  {
    id: "burgers",
    title: { fr: "Burgers", en: "Burgers", es: "Burgers" },
    note: {
      fr: "Sauces au choix : béarnaise · poivre · bleue",
      en: "Choice of sauce: béarnaise · pepper · blue cheese",
      es: "Salsa a elegir: bearnesa · pimienta · roquefort",
    },
    items: [
      { name: { fr: "Chicken Burger", en: "Chicken Burger", es: "Burger de Pollo" }, desc: { fr: "Poulet pané · sauce fromagère · salade · tomate · sauce végétale · sauce barbecue", en: "Breaded chicken · cheese sauce · lettuce · tomato · vegetable sauce · BBQ", es: "Pollo empanado · salsa de queso · lechuga · tomate · salsa vegetal · barbacoa" }, price: "14,50 €" },
      { name: { fr: "Original Burger", en: "Original Burger", es: "Burger Original" }, desc: { fr: "Steak haché 180 g · salade · tomate · sauce végétale · sauce cheddar", en: "180g beef patty · lettuce · tomato · vegetable sauce · cheddar sauce", es: "Hamburguesa 180g · lechuga · tomate · salsa vegetal · salsa cheddar" }, price: "15,00 €" },
      { name: { fr: "Bacon Burger", en: "Bacon Burger", es: "Burger Bacon" }, desc: { fr: "Steak haché · tranche bacon · salade · tomate", en: "Beef patty · bacon · lettuce · tomato", es: "Hamburguesa · bacon · lechuga · tomate" }, price: "16,00 €" },
    ],
  },
  {
    id: "tartares",
    title: { fr: "Tartares", en: "Tartares", es: "Tártaros" },
    items: [
      { name: { fr: "Tartare de bœuf", en: "Beef Tartare", es: "Tártaro de ternera" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "16,00 €" },
      { name: { fr: "Tartare de saumon", en: "Salmon Tartare", es: "Tártaro de salmón" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "15,00 €" },
    ],
  },
  {
    id: "snacks",
    title: { fr: "Snacks & Omelettes", en: "Snacks & Omelettes", es: "Snacks & Tortillas" },
    items: [
      { name: { fr: "Croque Monsieur", en: "Croque Monsieur", es: "Croque Monsieur" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "10,50 €" },
      { name: { fr: "Croque Madame", en: "Croque Madame", es: "Croque Madame" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "11,50 €" },
      { name: { fr: "Omelette nature", en: "Plain Omelette", es: "Tortilla francesa" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "10,50 €" },
      { name: { fr: "Omelette jambon", en: "Ham Omelette", es: "Tortilla de jamón" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "12,00 €" },
      { name: { fr: "Omelette fromage", en: "Cheese Omelette", es: "Tortilla de queso" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "12,00 €" },
      { name: { fr: "Omelette mixte", en: "Mixed Omelette", es: "Tortilla mixta" }, desc: { fr: "Frites et salade", en: "Fries and salad", es: "Patatas fritas y ensalada" }, price: "14,00 €" },
    ],
  },
  {
    id: "planches",
    title: { fr: "Nos Planches", en: "Sharing Boards", es: "Tablas para Compartir" },
    items: [
      { name: { fr: "Planche de fromage", en: "Cheese Board", es: "Tabla de quesos" }, price: "14,00 €" },
      { name: { fr: "Planche de charcuterie", en: "Charcuterie Board", es: "Tabla de embutidos" }, price: "14,50 €" },
      { name: { fr: "Planche mixte", en: "Mixed Board", es: "Tabla mixta" }, price: "17,00 €" },
      { name: { fr: "Assiette de frites", en: "Plate of Fries", es: "Ración de patatas fritas" }, price: "5,00 €" },
    ],
  },
  {
    id: "couscous",
    title: { fr: "Nos Couscous", en: "Our Couscous", es: "Nuestros Cuscuses" },
    note: {
      fr: "Servis sauf jeudi · vendredi · samedi · dimanche",
      en: "Served Monday to Wednesday only",
      es: "Servido solo de lunes a miércoles",
    },
    items: [
      { name: { fr: "Couscous Royal", en: "Royal Couscous", es: "Cuscús Real" }, desc: { fr: "Poulet · merguez · bœuf · brochette d'agneau", en: "Chicken · merguez · beef · lamb skewer", es: "Pollo · merguez · ternera · brocheta de cordero" }, price: "22,00 €" },
      { name: { fr: "Couscous Mixt", en: "Mixed Couscous", es: "Cuscús Mixto" }, desc: { fr: "Poulet merguez · bœuf merguez · brochette merguez", en: "Chicken merguez · beef merguez · merguez skewer", es: "Merguez de pollo · merguez de ternera · brocheta merguez" }, price: "18,00 €" },
      { name: { fr: "Couscous Méchaoui", en: "Mechoui Couscous", es: "Cuscús Mechui" }, price: "20,00 €" },
      { name: { fr: "Couscous Brochettes", en: "Skewer Couscous", es: "Cuscús Brochetas" }, price: "17,00 €" },
      { name: { fr: "Couscous Bœuf", en: "Beef Couscous", es: "Cuscús de Ternera" }, price: "15,00 €" },
      { name: { fr: "Couscous Poulet", en: "Chicken Couscous", es: "Cuscús de Pollo" }, price: "13,50 €" },
      { name: { fr: "Couscous Merguez", en: "Merguez Couscous", es: "Cuscús Merguez" }, price: "13,00 €" },
      { name: { fr: "Couscous Végétarien", en: "Vegetarian Couscous", es: "Cuscús Vegetariano" }, price: "12,00 €" },
    ],
  },
  {
    id: "desserts",
    title: { fr: "Desserts", en: "Desserts", es: "Postres" },
    items: [
      { name: { fr: "Île flottante", en: "Floating Island", es: "Isla flotante" }, price: "4,00 €" },
      { name: { fr: "Crème brûlée", en: "Crème brûlée", es: "Crema quemada" }, price: "5,00 €" },
      { name: { fr: "Tiramisu", en: "Tiramisu", es: "Tiramisú" }, price: "6,00 €" },
      { name: { fr: "Profiteroles", en: "Profiteroles", es: "Profiteroles" }, price: "7,00 €" },
      { name: { fr: "Fondant au chocolat", en: "Chocolate Fondant", es: "Coulant de chocolate" }, desc: { fr: "Servi avec 1 boule de glace vanille", en: "Served with 1 scoop of vanilla ice cream", es: "Servido con 1 bola de helado de vainilla" }, price: "7,00 €" },
      { name: { fr: "Glaces & sorbets", en: "Ice Cream & Sorbets", es: "Helados & Sorbetes" }, desc: { fr: "Vanille · chocolat · fraise · pomme · framboise · café · citron · noisette · menthe", en: "Vanilla · chocolate · strawberry · apple · raspberry · coffee · lemon · hazelnut · mint", es: "Vainilla · chocolate · fresa · manzana · frambuesa · café · limón · avellana · menta" }, price: "" },
    ],
  },
  {
    id: "softs",
    title: { fr: "Softs & Eaux", en: "Soft Drinks & Water", es: "Refrescos & Agua" },
    note: { fr: "Prix standard : 3,50 € — À table : 4,00 € (+0,50 €)", en: "Standard price: €3.50 — At table: €4.00 (+€0.50)", es: "Precio estándar: 3,50 € — En mesa: 4,00 € (+0,50 €)" },
    items: [
      { name: { fr: "Coca / Coca Zéro", en: "Coca-Cola / Coca-Cola Zero", es: "Coca-Cola / Coca-Cola Zero" }, price: "3,50 €" },
      { name: { fr: "Orangina", en: "Orangina", es: "Orangina" }, price: "3,50 €" },
      { name: { fr: "Limonade", en: "Lemonade", es: "Limonada" }, price: "3,50 €" },
      { name: { fr: "Ice Tea", en: "Ice Tea", es: "Té helado" }, price: "3,50 €" },
      { name: { fr: "Diabolo", en: "Diabolo", es: "Diabolo" }, price: "3,50 €" },
      { name: { fr: "Oasis Tropicale", en: "Oasis Tropical", es: "Oasis Tropical" }, price: "3,50 €" },
      { name: { fr: "Jus de fruit", en: "Fruit Juice", es: "Zumo de fruta" }, price: "3,50 €" },
      { name: { fr: "Perrier", en: "Perrier", es: "Perrier" }, price: "3,50 €" },
      { name: { fr: "Schweppes (tonic / agrumes)", en: "Schweppes (tonic / citrus)", es: "Schweppes (tónica / cítricos)" }, price: "3,50 €" },
      { name: { fr: "Vittel 50cl", en: "Vittel 50cl", es: "Vittel 50cl" }, price: "3,50 €" },
      { name: { fr: "Vittel 1L", en: "Vittel 1L", es: "Vittel 1L" }, price: "7,00 €" },
      { name: { fr: "San Pellegrino 50cl", en: "San Pellegrino 50cl", es: "San Pellegrino 50cl" }, price: "3,50 €" },
      { name: { fr: "San Pellegrino 1L", en: "San Pellegrino 1L", es: "San Pellegrino 1L" }, price: "7,00 €" },
    ],
  },
  {
    id: "bieres-pression",
    title: { fr: "Bières Pression", en: "Draft Beers", es: "Cervezas de Barril" },
    note: { fr: "25cl / 50cl", en: "25cl / 50cl", es: "25cl / 50cl" },
    items: [
      { name: { fr: "Stella Artois", en: "Stella Artois", es: "Stella Artois" }, price: "3,00 € / 6,00 €" },
      { name: { fr: "IPA 6°", en: "IPA 6°", es: "IPA 6°" }, price: "4,50 € / 8,50 €" },
      { name: { fr: "1664", en: "1664", es: "1664" }, price: "3,50 € / 7,00 €" },
      { name: { fr: "Leffe 6°", en: "Leffe 6°", es: "Leffe 6°" }, price: "4,00 € / 9,00 €" },
      { name: { fr: "Panaché", en: "Shandy", es: "Clara" }, price: "3,50 € / 7,00 €" },
      { name: { fr: "Monaco", en: "Monaco", es: "Monaco" }, price: "3,50 € / 7,00 €" },
    ],
  },
  {
    id: "bieres-bouteilles",
    title: { fr: "Bières Bouteilles", en: "Bottled Beers", es: "Cervezas de Botella" },
    items: [
      { name: { fr: "Corona 4° — 33cl", en: "Corona 4° — 33cl", es: "Corona 4° — 33cl" }, price: "4,50 €" },
      { name: { fr: "Desperados 4° — 33cl", en: "Desperados 4° — 33cl", es: "Desperados 4° — 33cl" }, price: "4,50 €" },
      { name: { fr: "Super Bock's 4° — 25cl", en: "Super Bock's 4° — 25cl", es: "Super Bock's 4° — 25cl" }, price: "4,50 €" },
      { name: { fr: "Heineken 5° — 25cl", en: "Heineken 5° — 25cl", es: "Heineken 5° — 25cl" }, price: "5,00 €" },
      { name: { fr: "Pelforth 6° — 33cl", en: "Pelforth 6° — 33cl", es: "Pelforth 6° — 33cl" }, price: "6,50 €" },
    ],
  },
  {
    id: "cafes",
    title: { fr: "Cafés & Thés", en: "Coffees & Teas", es: "Cafés & Tés" },
    note: { fr: "Expresso · Noisette · Allongé : Bar 1,50 € — Table 2,00 € — Terrasse 2,50 €", en: "Espresso · Noisette · Long: Bar €1.50 — Table €2.00 — Terrace €2.50", es: "Expreso · Noisette · Largo: Bar 1,50 € — Mesa 2,00 € — Terraza 2,50 €" },
    items: [
      { name: { fr: "Petit crème", en: "Small white coffee", es: "Café con leche pequeño" }, price: "3,50 €" },
      { name: { fr: "Grand crème", en: "Large white coffee", es: "Café con leche grande" }, price: "4,00 €" },
      { name: { fr: "Cappuccino", en: "Cappuccino", es: "Capuchino" }, price: "4,00 €" },
      { name: { fr: "Café Viennois", en: "Viennese Coffee", es: "Café Vienés" }, desc: { fr: "Espresso · chantilly maison · copeaux de chocolat", en: "Espresso · homemade whipped cream · chocolate shavings", es: "Expreso · nata montada casera · virutas de chocolate" }, price: "4,50 €" },
      { name: { fr: "Café Liégeois", en: "Café Liégeois", es: "Café Liégeois" }, desc: { fr: "Espresso · glace vanille · chantilly · copeaux de chocolat", en: "Espresso · vanilla ice cream · whipped cream · chocolate shavings", es: "Expreso · helado de vainilla · nata · virutas de chocolate" }, price: "4,50 €" },
      { name: { fr: "Thé", en: "Tea", es: "Té" }, price: "3,50 €" },
      { name: { fr: "Infusion", en: "Herbal tea", es: "Infusión" }, price: "3,50 €" },
      { name: { fr: "Petit chocolat chaud", en: "Small hot chocolate", es: "Chocolate caliente pequeño" }, price: "3,50 €" },
      { name: { fr: "Grand chocolat chaud", en: "Large hot chocolate", es: "Chocolate caliente grande" }, price: "4,00 €" },
      { name: { fr: "Irish Coffee", en: "Irish Coffee", es: "Irish Coffee" }, desc: { fr: "Café chaud · whiskey irlandais · sucre roux · crème légèrement fouettée", en: "Hot coffee · Irish whiskey · brown sugar · lightly whipped cream", es: "Café caliente · whisky irlandés · azúcar moreno · nata ligeramente montada" }, price: "8,00 €" },
    ],
  },
  {
    id: "aperitifs",
    title: { fr: "Apéritifs", en: "Aperitifs", es: "Aperitivos" },
    items: [
      { name: { fr: "Ricard", en: "Ricard", es: "Ricard" }, price: "3,50 €" },
      { name: { fr: "Pastis", en: "Pastis", es: "Pastis" }, price: "3,50 €" },
      { name: { fr: "Porto blanc ou rouge", en: "White or red Port", es: "Oporto blanco o tinto" }, price: "4,50 €" },
      { name: { fr: "Martini blanc ou rouge", en: "White or red Martini", es: "Martini blanco o rojo" }, price: "4,50 €" },
      { name: { fr: "Kir Sauvignon", en: "Kir Sauvignon", es: "Kir Sauvignon" }, price: "4,00 €" },
      { name: { fr: "Kir Chardonnay", en: "Kir Chardonnay", es: "Kir Chardonnay" }, price: "4,50 €" },
      { name: { fr: "Kir Royal", en: "Kir Royal", es: "Kir Royal" }, price: "8,00 €" },
      { name: { fr: "Kir Aveleda", en: "Kir Aveleda", es: "Kir Aveleda" }, desc: { fr: "Vinho Verde — vin blanc pétillant du Portugal", en: "Vinho Verde — sparkling white wine from Portugal", es: "Vinho Verde — vino blanco espumoso de Portugal" }, price: "3,50 €" },
    ],
  },
  {
    id: "vins-rouges",
    title: { fr: "Vins Rouges", en: "Red Wines", es: "Vinos Tintos" },
    note: { fr: "Au verre & à la bouteille", en: "By the glass & bottle", es: "Por copa y botella" },
    items: [
      { name: { fr: "Côtes du Rhône", en: "Côtes du Rhône", es: "Côtes du Rhône" }, desc: { fr: "14cl · 25cl · 50cl · 75cl", en: "14cl · 25cl · 50cl · 75cl", es: "14cl · 25cl · 50cl · 75cl" }, price: "3,50 € / 7 / 14 / 27 €" },
      { name: { fr: "Brouilly", en: "Brouilly", es: "Brouilly" }, desc: { fr: "14cl · 25cl · 50cl · 75cl", en: "14cl · 25cl · 50cl · 75cl", es: "14cl · 25cl · 50cl · 75cl" }, price: "4,50 € / 7 / 14 / 28 €" },
      { name: { fr: "Comtes de la Barde — Bordeaux Saint-Émilion", en: "Comtes de la Barde — Bordeaux Saint-Émilion", es: "Comtes de la Barde — Bordeaux Saint-Émilion" }, desc: { fr: "75cl", en: "75cl", es: "75cl" }, price: "45,00 €" },
      { name: { fr: "Saint-Estèphe — Médoc", en: "Saint-Estèphe — Médoc", es: "Saint-Estèphe — Médoc" }, desc: { fr: "75cl", en: "75cl", es: "75cl" }, price: "45,00 €" },
      { name: { fr: "Brouilly du Beaujolais", en: "Brouilly du Beaujolais", es: "Brouilly del Beaujolais" }, desc: { fr: "75cl", en: "75cl", es: "75cl" }, price: "38,00 €" },
      { name: { fr: "Cambras — Merlot · Cabernet Sauvignon", en: "Cambras — Merlot · Cabernet Sauvignon", es: "Cambras — Merlot · Cabernet Sauvignon" }, desc: { fr: "75cl", en: "75cl", es: "75cl" }, price: "27,00 €" },
      { name: { fr: "Languedoc Les Darons", en: "Languedoc Les Darons", es: "Languedoc Les Darons" }, desc: { fr: "75cl", en: "75cl", es: "75cl" }, price: "27,00 €" },
      { name: { fr: "Pinot Noir Ropiteau", en: "Pinot Noir Ropiteau", es: "Pinot Noir Ropiteau" }, desc: { fr: "75cl", en: "75cl", es: "75cl" }, price: "27,00 €" },
    ],
  },
  {
    id: "vins-blancs",
    title: { fr: "Vins Blancs", en: "White Wines", es: "Vinos Blancos" },
    note: { fr: "Au verre & à la bouteille", en: "By the glass & bottle", es: "Por copa y botella" },
    items: [
      { name: { fr: "Sauvignon", en: "Sauvignon", es: "Sauvignon" }, desc: { fr: "14cl · 25cl · 50cl · 75cl", en: "14cl · 25cl · 50cl · 75cl", es: "14cl · 25cl · 50cl · 75cl" }, price: "4,00 € / 7 / 14 / 27 €" },
      { name: { fr: "Chardonnay", en: "Chardonnay", es: "Chardonnay" }, desc: { fr: "14cl · 25cl · 50cl · 75cl", en: "14cl · 25cl · 50cl · 75cl", es: "14cl · 25cl · 50cl · 75cl" }, price: "4,50 € / 7,50 / 14,50 / 27 €" },
      { name: { fr: "Aveleda Vinho Verde (Portugal)", en: "Aveleda Vinho Verde (Portugal)", es: "Aveleda Vinho Verde (Portugal)" }, desc: { fr: "14cl · 50cl", en: "14cl · 50cl", es: "14cl · 50cl" }, price: "3,00 € / 20,00 €" },
      { name: { fr: "Chablis", en: "Chablis", es: "Chablis" }, desc: { fr: "50cl", en: "50cl", es: "50cl" }, price: "39,00 €" },
      { name: { fr: "Gris Blanc", en: "Gris Blanc", es: "Gris Blanc" }, desc: { fr: "50cl", en: "50cl", es: "50cl" }, price: "25,00 €" },
    ],
  },
  {
    id: "vins-roses",
    title: { fr: "Vins Rosés", en: "Rosé Wines", es: "Vinos Rosados" },
    items: [
      { name: { fr: "Montaubria", en: "Montaubria", es: "Montaubria" }, price: "25,00 €" },
      { name: { fr: "Côtes de Provence", en: "Côtes de Provence", es: "Côtes de Provence" }, price: "21,00 €" },
      { name: { fr: "La Santonnière", en: "La Santonnière", es: "La Santonnière" }, price: "26,00 €" },
      { name: { fr: "Côtes de Provence — Cave de Roquefort", en: "Côtes de Provence — Cave de Roquefort", es: "Côtes de Provence — Cave de Roquefort" }, price: "38,00 €" },
      { name: { fr: "Mateus (Portugal)", en: "Mateus (Portugal)", es: "Mateus (Portugal)" }, price: "18,00 €" },
      { name: { fr: "Moulin de Maures", en: "Moulin de Maures", es: "Moulin de Maures" }, price: "25,00 €" },
      { name: { fr: "Boulaouane", en: "Boulaouane", es: "Boulaouane" }, price: "25,00 €" },
      { name: { fr: "Tlemcen Gris Blanc", en: "Tlemcen Gris Blanc", es: "Tlemcen Gris Blanc" }, price: "26,00 €" },
      { name: { fr: "Minuty", en: "Minuty", es: "Minuty" }, price: "48,00 €" },
    ],
  },
  {
    id: "vins-algeriens",
    title: { fr: "Vins Algériens", en: "Algerian Wines", es: "Vinos Argelinos" },
    items: [
      { name: { fr: "Coteaux de Mascara", en: "Coteaux de Mascara", es: "Coteaux de Mascara" }, price: "22,00 €" },
      { name: { fr: "Cuvée de Tlemcen", en: "Cuvée de Tlemcen", es: "Cuvée de Tlemcen" }, price: "25,00 €" },
      { name: { fr: "Montaubria", en: "Montaubria", es: "Montaubria" }, price: "26,00 €" },
      { name: { fr: "Saint Augustin", en: "Saint Augustin", es: "Saint Augustin" }, price: "26,00 €" },
    ],
  },
  {
    id: "vins-marocains",
    title: { fr: "Vins Marocains", en: "Moroccan Wines", es: "Vinos Marroquíes" },
    items: [
      { name: { fr: "Boulaouane", en: "Boulaouane", es: "Boulaouane" }, desc: { fr: "37cl / 75cl", en: "37cl / 75cl", es: "37cl / 75cl" }, price: "18,50 € / 22,00 €" },
    ],
  },
  {
    id: "whiskies",
    title: { fr: "Whiskies", en: "Whiskies", es: "Whiskies" },
    note: { fr: "2cl / 4cl", en: "2cl / 4cl", es: "2cl / 4cl" },
    items: [
      { name: { fr: "J&B", en: "J&B", es: "J&B" }, price: "3,00 € / 7,00 €" },
      { name: { fr: "Clan Campbell — Blended Scotch, Highlands", en: "Clan Campbell — Blended Scotch, Highlands", es: "Clan Campbell — Blended Scotch, Highlands" }, price: "3,00 € / 6,00 €" },
      { name: { fr: "Johnnie Walker", en: "Johnnie Walker", es: "Johnnie Walker" }, price: "4,00 € / 8,00 €" },
      { name: { fr: "Jack Daniel's", en: "Jack Daniel's", es: "Jack Daniel's" }, price: "4,00 € / 9,00 €" },
      { name: { fr: "Chivas Regal", en: "Chivas Regal", es: "Chivas Regal" }, price: "3,50 € / 8,00 €" },
    ],
  },
  {
    id: "digestifs",
    title: { fr: "Digestifs", en: "Digestifs", es: "Digestivos" },
    items: [
      { name: { fr: "Cognac / Calvados", en: "Cognac / Calvados", es: "Coñac / Calvados" }, price: "4,00 €" },
      { name: { fr: "Poire Williams", en: "Poire Williams", es: "Poire Williams" }, price: "6,00 €" },
      { name: { fr: "Get 27 / Get 31", en: "Get 27 / Get 31", es: "Get 27 / Get 31" }, price: "6,00 €" },
      { name: { fr: "Baileys", en: "Baileys", es: "Baileys" }, price: "6,00 €" },
      { name: { fr: "Amaretto / Cointreau", en: "Amaretto / Cointreau", es: "Amaretto / Cointreau" }, price: "6,00 €" },
      { name: { fr: "Diplomático", en: "Diplomático", es: "Diplomático" }, price: "11,00 €" },
      { name: { fr: "Bumbu", en: "Bumbu", es: "Bumbu" }, desc: { fr: "Rhum artisanal des Caraïbes", en: "Artisanal Caribbean rum", es: "Ron artesanal del Caribe" }, price: "11,00 €" },
      { name: { fr: "De papa", en: "De papa", es: "De papa" }, price: "11,00 €" },
      { name: { fr: "Gin / Vodka / Tequila / Rhum (4cl)", en: "Gin / Vodka / Tequila / Rum (4cl)", es: "Ginebra / Vodka / Tequila / Ron (4cl)" }, price: "6,00 €" },
    ],
  },
];
